language: node_js
node_js:
  - stable
  - 5
  - 4
  - 3
  - 2
  - 1
  - 0.12
cache:
  directories:
    - node_modules
script:
  - npm test
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov